/**
    Update your config settings the .env file. Do not edit this file.
    This file sets up general config options based on .env.
 */

if (!process.env.CLIENT_ID || !process.env.CLIENT_SECRET) {
  console.log(
    "Please fill out the settings in the .env file to connect with Gopher"
  );
  process.exit();
}

const extensionUrl = process.env.EXTENSION_URL;
const clientId = process.env.CLIENT_ID;
const clientSecret = process.env.CLIENT_SECRET;
const apiHost = process.env.API_HOST || "https://api.gopher.email/";
const gopherAdmin = process.env.GOPHER_ADMIN || "https://app.gopher.email/";
const scope = process.env.SCOPE || "get_user_info extension_manage_self";
const redirectUrl =
  process.env.REDIRECT_URI ||
  "https://" + process.env.PROJECT_DOMAIN + ".glitch.me/auth/callback";

module.exports = {
  extensionUrl: extensionUrl,
  apiHost: apiHost,
  clientId: clientId,
  clientSecret: clientSecret,
  redirectUri: redirectUrl,
  tokenHost: apiHost,
  tokenPath: apiHost + "api/v1/oauth2/access_token",
  authorizePath: gopherAdmin + "authorize-extension",
  scope: scope
};
